# Generated by Django 2.2.3 on 2019-08-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='role',
            new_name='roles',
        ),
    ]
