# Generated by Django 2.2.3 on 2019-09-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20190912_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='img',
            field=models.ImageField(upload_to='D:\\soft_install\\python3\\python3.7\\PerfectCRM\\Perfectcrm\\statics\\img\\Video', verbose_name='图片'),
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('d_2_c', models.ManyToManyField(to='crm.Category')),
            ],
        ),
    ]
